### ISSUE TITLE
Discord inv doesn't render properly on certain devices and resolutions

### ISSUE THREAD

**Issue by HyperCodec** [tungsten-client/tungsten-frontend#7]
![image](https://github.com/tungsten-client/tungesten-frontend/assets/72839119/4dcb1993-608c-4f06-a1a7-0b85428b9ca6)

SS taken from mobile

**Comment by HyperCodec** [comment]
Also the menu thingy looks weird asf on mobile

**Comment by stdcout1** [comment]
fixed with latest commit
